/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.officefurniturecompany.GUI;

import com.mycompany.officefurniturecompany.Basket;
import com.mycompany.officefurniturecompany.Chair;
import com.mycompany.officefurniturecompany.Desk;
import com.mycompany.officefurniturecompany.Furniture;
import com.mycompany.officefurniturecompany.Table;
import com.mycompany.officefurniturecompany.WoodType;
import com.mycompany.officefurniturecompany.baseType;
import java.io.File;
import javax.swing.JOptionPane;
import java.util.HashSet;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;

/**
 *
 * @author thoma
 */
public class Main extends javax.swing.JFrame {
    private Basket basket = new Basket();
    private HashSet<String> idNumbers = new HashSet();
    
    private DefaultListModel dm = new DefaultListModel();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        addChairButton = new javax.swing.JButton();
        addTableButton = new javax.swing.JButton();
        addDeskButton = new javax.swing.JButton();
        showSummaryButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        basketPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        basketGrid = new javax.swing.JList<>();
        deskFormPanel = new javax.swing.JPanel();
        deskPicPanel = new javax.swing.JPanel();
        deskPicLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        deskIdField = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        deskTypeOfWoodField = new javax.swing.JComboBox<>();
        deskQuantityField = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        drawersField = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        deskWidthField = new javax.swing.JSpinner();
        deskDepthField = new javax.swing.JSpinner();
        addDesktoBasketBtn = new javax.swing.JButton();
        tableFormPanel = new javax.swing.JPanel();
        tablePicPanel = new javax.swing.JPanel();
        tableIdField = new javax.swing.JFormattedTextField();
        tableTypeOfWoodField = new javax.swing.JComboBox<>();
        tableQuantityField = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tableBaseTypeField = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        addTabletoBasketBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tableDiameterField = new javax.swing.JSpinner();
        chairFormPanel = new javax.swing.JPanel();
        chairPicPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addChairtoBasketBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        chairTypeOfWoodField = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        armRestsBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        chairQuantityField = new javax.swing.JComboBox<>();
        chairIdField = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        basketButton = new javax.swing.JButton();
        saveBasketBtn = new javax.swing.JButton();
        loadBasketBtn = new javax.swing.JButton();
        clearBasketBtn = new javax.swing.JButton();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 204, 204));
        jPanel9.setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1208, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 70));

        buttonPanel.setBackground(new java.awt.Color(255, 204, 204));
        buttonPanel.setBorder(new javax.swing.border.MatteBorder(null));

        addChairButton.setText("Add new chair");
        addChairButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChairButtonActionPerformed(evt);
            }
        });

        addTableButton.setText("Add new table");
        addTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTableButtonActionPerformed(evt);
            }
        });

        addDeskButton.setText("Add new desk");
        addDeskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDeskButtonActionPerformed(evt);
            }
        });

        showSummaryButton.setText("Show summmary");
        showSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSummaryButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addTableButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addChairButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(buttonPanelLayout.createSequentialGroup()
                        .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(addDeskButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showSummaryButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(10, Short.MAX_VALUE))))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(addChairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(addTableButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(addDeskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(showSummaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        jPanel8.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 150, 760));

        basketGrid.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        basketGrid.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        basketGrid.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        basketGrid.setVisibleRowCount(-1);
        jScrollPane1.setViewportView(basketGrid);

        javax.swing.GroupLayout basketPanelLayout = new javax.swing.GroupLayout(basketPanel);
        basketPanel.setLayout(basketPanelLayout);
        basketPanelLayout.setHorizontalGroup(
            basketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        basketPanelLayout.setVerticalGroup(
            basketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab1", basketPanel);

        deskFormPanel.setBackground(new java.awt.Color(255, 204, 102));

        deskPicPanel.setPreferredSize(new java.awt.Dimension(329, 280));

        deskPicLabel.setText("desk pic here");

        javax.swing.GroupLayout deskPicPanelLayout = new javax.swing.GroupLayout(deskPicPanel);
        deskPicPanel.setLayout(deskPicPanelLayout);
        deskPicPanelLayout.setHorizontalGroup(
            deskPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );
        deskPicPanelLayout.setVerticalGroup(
            deskPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deskPicLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );

        jLabel11.setBackground(new java.awt.Color(0, 0, 204));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("ID Number(####):");

        try {
            deskIdField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        deskIdField.setToolTipText("Enter the 4 digit product ID  ");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Type of wood:");

        deskTypeOfWoodField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OAK", "WALNUT" }));

        deskQuantityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Quantity:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Width(CM):");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Depth(CM):");

        drawersField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Number of drawers:");

        deskWidthField.setModel(new javax.swing.SpinnerNumberModel(100, 100, 500, 10));
        deskWidthField.setToolTipText("Click to edit Width");

        deskDepthField.setModel(new javax.swing.SpinnerNumberModel(40, 0, 500, 1));
        deskDepthField.setToolTipText("Click to edit depth");

        addDesktoBasketBtn.setText("Add to basket");
        addDesktoBasketBtn.setToolTipText("Click to add the current item(s) to the basket");
        addDesktoBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDesktoBasketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deskFormPanelLayout = new javax.swing.GroupLayout(deskFormPanel);
        deskFormPanel.setLayout(deskFormPanelLayout);
        deskFormPanelLayout.setHorizontalGroup(
            deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskFormPanelLayout.createSequentialGroup()
                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskFormPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(deskPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(deskFormPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)
                        .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(deskDepthField)
                            .addComponent(deskIdField, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(deskTypeOfWoodField, 0, 165, Short.MAX_VALUE)
                            .addComponent(deskWidthField))
                        .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(deskFormPanelLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drawersField, 0, 82, Short.MAX_VALUE)
                                    .addComponent(deskQuantityField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(deskFormPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addDesktoBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(77, 77, 77))
        );
        deskFormPanelLayout.setVerticalGroup(
            deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deskFormPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(deskPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deskIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deskQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(37, 37, 37)
                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(deskTypeOfWoodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(drawersField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deskWidthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(deskFormPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(deskFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(deskDepthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deskFormPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(addDesktoBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        jTabbedPane1.addTab("tab3", deskFormPanel);

        tableFormPanel.setBackground(new java.awt.Color(255, 255, 153));

        tablePicPanel.setPreferredSize(new java.awt.Dimension(329, 280));

        javax.swing.GroupLayout tablePicPanelLayout = new javax.swing.GroupLayout(tablePicPanel);
        tablePicPanel.setLayout(tablePicPanelLayout);
        tablePicPanelLayout.setHorizontalGroup(
            tablePicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        tablePicPanelLayout.setVerticalGroup(
            tablePicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        try {
            tableIdField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tableIdField.setToolTipText("Enter the 4 digit product ID  ");

        tableTypeOfWoodField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OAK", "WALNUT" }));
        tableTypeOfWoodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableTypeOfWoodFieldActionPerformed(evt);
            }
        });

        tableQuantityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel5.setBackground(new java.awt.Color(0, 0, 204));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("ID Number(####):");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Type of wood:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Diameter(CM):");

        tableBaseTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHROME", "WOODEN" }));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Base Type:");

        addTabletoBasketBtn.setText("Add to basket");
        addTabletoBasketBtn.setToolTipText("Click to add the current item(s) to the basket");
        addTabletoBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTabletoBasketBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Quantity:");

        tableDiameterField.setModel(new javax.swing.SpinnerNumberModel(50, 50, 300, 10));
        tableDiameterField.setToolTipText("Click to edit Diameter");

        javax.swing.GroupLayout tableFormPanelLayout = new javax.swing.GroupLayout(tableFormPanel);
        tableFormPanel.setLayout(tableFormPanelLayout);
        tableFormPanelLayout.setHorizontalGroup(
            tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableFormPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(tableFormPanelLayout.createSequentialGroup()
                        .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tableTypeOfWoodField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(tableFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tableIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tableBaseTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(tablePicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(addTabletoBasketBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(tableQuantityField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableDiameterField))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        tableFormPanelLayout.setVerticalGroup(
            tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableFormPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(tablePicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tableFormPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tableTypeOfWoodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(tableFormPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tableDiameterField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19)
                .addGroup(tableFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tableBaseTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(addTabletoBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("tab4", tableFormPanel);

        chairFormPanel.setBackground(new java.awt.Color(204, 204, 255));

        chairPicPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout chairPicPanelLayout = new javax.swing.GroupLayout(chairPicPanel);
        chairPicPanel.setLayout(chairPicPanelLayout);
        chairPicPanelLayout.setHorizontalGroup(
            chairPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );
        chairPicPanelLayout.setVerticalGroup(
            chairPicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ID Number(####):");

        addChairtoBasketBtn.setText("Add to basket");
        addChairtoBasketBtn.setToolTipText("Click to add the current item(s) to the basket");
        addChairtoBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addChairtoBasketBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Type of wood:");

        chairTypeOfWoodField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "OAK", "WALNUT" }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Armrests");

        armRestsBox.setToolTipText("Check box only if armrests are required");
        armRestsBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armRestsBoxActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Quantity:");

        chairQuantityField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        try {
            chairIdField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        chairIdField.setToolTipText("Enter the 4 digit product ID  ");

        javax.swing.GroupLayout chairFormPanelLayout = new javax.swing.GroupLayout(chairFormPanel);
        chairFormPanel.setLayout(chairFormPanelLayout);
        chairFormPanelLayout.setHorizontalGroup(
            chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chairFormPanelLayout.createSequentialGroup()
                .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(chairFormPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addChairtoBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(chairFormPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chairFormPanelLayout.createSequentialGroup()
                                .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(chairFormPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(chairTypeOfWoodField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(chairFormPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(28, 28, 28)
                                        .addComponent(chairIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chairQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chairPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(chairFormPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(armRestsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(202, 202, 202)))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        chairFormPanelLayout.setVerticalGroup(
            chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chairFormPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(chairPicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(chairQuantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chairTypeOfWoodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(chairFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(armRestsBox, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addChairtoBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("tab2", chairFormPanel);

        jPanel8.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 820, 680));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        basketButton.setText("Show Basket");
        basketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basketButtonActionPerformed(evt);
            }
        });

        saveBasketBtn.setText("Save basket");
        saveBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBasketBtnActionPerformed(evt);
            }
        });

        loadBasketBtn.setText("Load Basket");
        loadBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBasketBtnActionPerformed(evt);
            }
        });

        clearBasketBtn.setText("Clear basket");
        clearBasketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBasketBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(saveBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(loadBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(clearBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basketButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBasketBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel8.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 720, 820, 110));

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSummaryButtonActionPerformed
        // TODO add your handling code here:
        basket.createSummary();
    }//GEN-LAST:event_showSummaryButtonActionPerformed

    private void addChairButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChairButtonActionPerformed
        // TODO add your handling code here:    
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_addChairButtonActionPerformed

    private void addChairtoBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addChairtoBasketBtnActionPerformed
       //this currently works but not if the box is left blank before the first press
        if(!chairIdField.getText().isBlank()){
            if(idNumbers.contains(chairIdField.getText())){
                JOptionPane.showMessageDialog(rootPane, "That ID number is already in use");
            }else{
                idNumbers.add(chairIdField.getText());
           
                String idNumber = chairIdField.getText();
                int quantity = chairQuantityField.getSelectedIndex()+1;
                boolean armRest = armRestsBox.isSelected();
                WoodType wood = WoodType.valueOf(chairTypeOfWoodField.getItemAt(chairTypeOfWoodField.getSelectedIndex()));

                Chair chair = new Chair(idNumber, wood, quantity, armRest);
                
                chair.calculatePrice();
                basket.addToBasket(chair);
                System.out.println("the following items are in the basket");
                //could do with some sort of feedback here to let user know that the item has been added to basket
                basket.createSummary();
                dm.addElement(chair);
                
                
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please ensure all fields are filled before adding to basket");
        }
            
            
        
        
   
    }//GEN-LAST:event_addChairtoBasketBtnActionPerformed

    private void armRestsBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armRestsBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_armRestsBoxActionPerformed

    private void addTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTableButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        //tableDiameterField.setInputVerifier(new DiameterVerifier());
        //tableIdField.setInputVerifier(new IdVerifier());
        
        
    }//GEN-LAST:event_addTableButtonActionPerformed

    private void addDeskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDeskButtonActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_addDeskButtonActionPerformed

    private void basketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basketButtonActionPerformed
        // TODO add your handling code here:
        //show the correct tabbed pane for the basket menu
        
        jTabbedPane1.setSelectedIndex(0);
        //create a new basket renderer object
        basketGrid.setCellRenderer(new basketRenderer());
        
        //set the model of the basket list field to be based on the default list model that contains the furniture objects
        //could this model be set from the basketItems list within the basket class?
        basketGrid.setModel(dm);
        
        
    }//GEN-LAST:event_basketButtonActionPerformed

    private void tableTypeOfWoodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableTypeOfWoodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableTypeOfWoodFieldActionPerformed

    private void addTabletoBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTabletoBasketBtnActionPerformed

        if(!tableIdField.getText().isBlank()){
            if(idNumbers.contains(tableIdField.getText())){
                JOptionPane.showMessageDialog(rootPane, "That ID number is already in use");
            }else{
                idNumbers.add(tableIdField.getText());
                
                String idNumber = tableIdField.getText();
                int diameter = Integer.valueOf(tableDiameterField.getValue().toString());
                
                
                WoodType wood = WoodType.valueOf(tableTypeOfWoodField.getItemAt(tableTypeOfWoodField.getSelectedIndex()));
                int quantity = tableQuantityField.getSelectedIndex()+1;
                baseType base = baseType.valueOf(tableBaseTypeField.getItemAt(tableBaseTypeField.getSelectedIndex()));
                
                Table table = new Table(idNumber, wood, quantity, base, diameter);
                table.calculatePrice();
                basket.addToBasket(table);
                
                
                System.out.println("the following items are in the basket " );
                basket.createSummary();
                dm.addElement(table);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Id Field must be 4 digits long");
        }
                
         
    }//GEN-LAST:event_addTabletoBasketBtnActionPerformed

    private void addDesktoBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDesktoBasketBtnActionPerformed
        // TODO add your handling code here:
        if (!deskIdField.getText().isBlank()){
            if (idNumbers.contains(deskIdField.getText())){
                JOptionPane.showMessageDialog(rootPane, "That ID number is already in use");
            }else {
                idNumbers.add(deskIdField.getText());
                
                String idNumber = deskIdField.getText();
                WoodType wood = WoodType.valueOf(deskTypeOfWoodField.getItemAt(deskTypeOfWoodField.getSelectedIndex()));
                int quantity = deskQuantityField.getSelectedIndex()+1;
                int width = Integer.valueOf(deskWidthField.getValue().toString());
                int depth  = Integer.valueOf(deskWidthField.getValue().toString());
                
               
                
                int drawers = drawersField.getSelectedIndex()+1;
                
                Desk desk = new Desk(idNumber, wood, quantity, width, depth, drawers );
                desk.calculatePrice();
                basket.addToBasket(desk);
                
                System.out.println("the following items are in the basket " );
                basket.createSummary();
                
                dm.addElement(desk);
  
            }
        }else {
            JOptionPane.showMessageDialog(rootPane, "Id Field must be 4 digits long");
        }
    }//GEN-LAST:event_addDesktoBasketBtnActionPerformed

    private void loadBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBasketBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setCurrentDirectory(new File("."));
        
        int a = fileChooser.showOpenDialog(null);
        if(a == JFileChooser.APPROVE_OPTION){
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            
            basket.emptyBasket();
            dm.clear();
            //add the loaded basket into the empty basket
            basket = basket.loadBasket(file);
            //iterate over the new basket and add the furniture objects into the list model so they can be rendered
            for(int i = 0; i < basket.getBasketItems().size(); i++){
                Furniture furniture = basket.getBasketItems().get(i);
                dm.addElement(furniture);
                
            }
            System.out.println("the new basket is ");
            basket.createSummary();
            
        }
    }//GEN-LAST:event_loadBasketBtnActionPerformed

    private void clearBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBasketBtnActionPerformed
        // TODO add your handling code here:
        int dialog = JOptionPane.showConfirmDialog(rootPane, "are you sure you want to clear the basket?");
        if(dialog == JOptionPane.YES_OPTION){
             basket.emptyBasket();
             dm.clear();
             System.out.println("the current basket after clearing is");
             basket.createSummary();
        } 
    }//GEN-LAST:event_clearBasketBtnActionPerformed

    private void saveBasketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBasketBtnActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("."));
        int a = fileChooser.showSaveDialog(null);
        if(a == JFileChooser.APPROVE_OPTION){
            File file = new File(fileChooser.getSelectedFile().getAbsolutePath());
            basket.saveBasket(file);
        
        }
    }//GEN-LAST:event_saveBasketBtnActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addChairButton;
    private javax.swing.JButton addChairtoBasketBtn;
    private javax.swing.JButton addDeskButton;
    private javax.swing.JButton addDesktoBasketBtn;
    private javax.swing.JButton addTableButton;
    private javax.swing.JButton addTabletoBasketBtn;
    private javax.swing.JCheckBox armRestsBox;
    private javax.swing.JButton basketButton;
    private javax.swing.JList<String> basketGrid;
    private javax.swing.JPanel basketPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel chairFormPanel;
    private javax.swing.JFormattedTextField chairIdField;
    private javax.swing.JPanel chairPicPanel;
    private javax.swing.JComboBox<String> chairQuantityField;
    private javax.swing.JComboBox<String> chairTypeOfWoodField;
    private javax.swing.JButton clearBasketBtn;
    private javax.swing.JSpinner deskDepthField;
    private javax.swing.JPanel deskFormPanel;
    private javax.swing.JFormattedTextField deskIdField;
    private javax.swing.JLabel deskPicLabel;
    private javax.swing.JPanel deskPicPanel;
    private javax.swing.JComboBox<String> deskQuantityField;
    private javax.swing.JComboBox<String> deskTypeOfWoodField;
    private javax.swing.JSpinner deskWidthField;
    private javax.swing.JComboBox<String> drawersField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    private javax.swing.JButton loadBasketBtn;
    private javax.swing.JButton saveBasketBtn;
    private javax.swing.JButton showSummaryButton;
    private javax.swing.JComboBox<String> tableBaseTypeField;
    private javax.swing.JSpinner tableDiameterField;
    private javax.swing.JPanel tableFormPanel;
    private javax.swing.JFormattedTextField tableIdField;
    private javax.swing.JPanel tablePicPanel;
    private javax.swing.JComboBox<String> tableQuantityField;
    private javax.swing.JComboBox<String> tableTypeOfWoodField;
    // End of variables declaration//GEN-END:variables
}
